name: Bundle
on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'bundle/darklua.config'
      - 'rokit.toml'
      - 'selene.toml'

jobs:
  build:
    strategy:
      matrix:
        platform: 
          - {name: windows, os: windows-2022}
          - {name: linux, os: ubuntu-22.04}
        arch: [x86_64, aarch64]
    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: CompeyDev/setup-rokit@v0.1.2
        with:
          version: v1.2.0
          cache: false
          token: ${{ github.token }}
      
      - name: Bundle Files
        run: darklua process src/Repackage.luau bundle/Bundled.luau -c bundle/darklua.config

      - name: Build (Windows)
        if: matrix.platform.name == 'windows'
        run: lune build bundle/Bundled.luau -o bundle/Repackage-${{ matrix.arch }}.exe -t windows-${{ matrix.arch }}
      
      - name: Build (Linux)
        if: matrix.platform.name == 'linux'
        run: lune build bundle/Bundled.luau -o bundle/Repackage-${{ matrix.arch }} -t linux-${{ matrix.arch }}
          
      - name: Upload Bundle Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Repackage-${{ matrix.platform.name }}-${{ matrix.arch }}
          path: bundle/Repackage*